// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxzbxvtjxpjhoqjzmkrq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54emJ4dnRqeHBqaG9xanpta3JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMjM2OTAsImV4cCI6MjA1Njg5OTY5MH0.sROjmbl8ROzFvmWC9SJjz9MQzGuCq5QfpsuS7-gM_ZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);