// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyywzijkpsnwjierldqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5eXd6aWprcHNud2ppZXJsZHF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NDkwMDAsImV4cCI6MjA1OTEyNTAwMH0.uyy78O50XUkTlbIVByqs-P0eqN5NV883ihQsrHzqOeE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);